work_dir: ./work_dir/ntu120/xsub/joint

# feeder
feeder: feeders.feeder_MMCL.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  object_path: /private/PKU/dataset/xxxx/BLIP-main/output/object/
  image_path: /private/PKU/dataset/xxxx/BLIP-main/save_img/ALL_img/
  sample_path: /private/PKU/dataset/xxxx/BLIP-main/ntu120_XSub_train.txt
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  object_path: /private/PKU/dataset/xxxx/BLIP-main/output/object/
  image_path: /private/PKU/dataset/xxxx/BLIP-main/save_img/ALL_img/
  sample_path: /private/PKU/dataset/xxxx/BLIP-main/ntu120_XSub_val.txt
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.MMCL.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [90, 100]
warm_up_epoch: 5

# training
device: [0, 1]
batch_size: 200
test_batch_size: 200
num_epoch: 110
nesterov: True
